Traceback (most recent call last):
  File "/well/win-fmrib-analysis/users/gqu790/moval/moval_scripts/eval_seg3d_brainlesion.py", line 269, in <module>
    main()
  File "/well/win-fmrib-analysis/users/gqu790/moval/moval_scripts/eval_seg3d_brainlesion.py", line 213, in main
    GTimg           = GT_read.get_fdata()           # ``(H, W, D)``
  File "/well/win-fmrib-analysis/users/gqu790/conda/skylake/envs/moval/lib/python3.8/site-packages/nibabel/dataobj_images.py", line 373, in get_fdata
    data = np.asanyarray(self._dataobj, dtype=dtype)
  File "/well/win-fmrib-analysis/users/gqu790/conda/skylake/envs/moval/lib/python3.8/site-packages/nibabel/arrayproxy.py", line 457, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/well/win-fmrib-analysis/users/gqu790/conda/skylake/envs/moval/lib/python3.8/site-packages/nibabel/arrayproxy.py", line 426, in _get_scaled
    scaled = scaled.astype(np.promote_types(scaled.dtype, dtype), copy=False)
numpy.core._exceptions.MemoryError: Unable to allocate 66.2 MiB for an array with shape (197, 233, 189) and data type float64
