fsl_sub/2.7(12):ERROR:150: Module 'fsl_sub/2.7' conflicts with the currently loaded module(s) 'fsl_sub/2.8.4'
fsl_sub/2.7(12):ERROR:102: Tcl command execution failed: conflict fsl_sub

Traceback (most recent call last):
  File "/well/win-fmrib-analysis/users/gqu790/moval/moval_scripts/eval_seg3d_prostate_ensemble.py", line 101, in <module>
    main()
  File "/well/win-fmrib-analysis/users/gqu790/moval/moval_scripts/eval_seg3d_prostate_ensemble.py", line 74, in main
    err_test, metric_estim, metric_real = test_cls(
  File "/gpfs3/well/win-fmrib-analysis/users/gqu790/moval/moval_scripts/eval_seg3d_brainlesion_ensemble.py", line 65, in test_cls
    logits_test_crop, gt_guide_test_crop = moval_model.crop(logits = logits_test, gt = gt_guide_test, approximate_boundary = 30)
  File "/well/win-fmrib-analysis/users/gqu790/conda/skylake/envs/moval/lib/python3.8/site-packages/moval/integrations/sklearn/moval.py", line 446, in crop
    if len(gt_map.shape) == 2:
AttributeError: 'list' object has no attribute 'shape'
